name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: vikash98yadav
  DOCKER_PASSWORD: Vikash@17apr
  DOCKER_REPO: vikash98yadav
  IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: ${{ env.DOCKER_REPO }}:${{ env.IMAGE_TAG }}
        build-args: |
          - ARG1=value1
          - ARG2=value2

    - name: Start GraphSpace container and check health controller response
      run: docker compose up -d

    - name: Show Running Containers
      run: docker ps

    - name: Wait
      run: sleep 10s

    - name: Check health of containers
      run: docker-compose ps && docker-compose exec -T web python -c "print('Application is running')"

    - name: Push Docker image to Docker Hub
      run: |
        docker tag ${env.ECR_REPO}:${env.IMAGE_TAG} ${env.DOCKER_USERNAME}/${env.DOCKER_REPO}:${env.IMAGE_TAG}
        docker push ${env.DOCKER_USERNAME}/${env.DOCKER_REPO}:${env.IMAGE_TAG}

    - name: Shut Down Docker Containers
      run: docker-compose down
