name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: vikash98yadav
        DOCKER_PASSWORD: Vikash@17apr
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vikash98yadav/githubtwin:$(date +%s)
      
    - name: Docker Push
      run: docker push vikash98yadav/GithubTwin
