name: Docker Build, Run and Push

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: vikash98yadav
  DOCKER_PASSWORD: Vikash@17apr
  DOCKER_REPO: GitHubTwin
  IMAGE_TAG: latest

jobs:
  build-run-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${env.DOCKER_REPO}:${env.IMAGE_TAG} .

    - name: Start GraphSpace container and check health controller response
      run: docker run -d --name twin -p 8000:8000 ${env.DOCKER_REPO}/twin:${env.IMAGE_TAG}

    - name: Show Running Containers
      run: docker ps

    - name: Wait
      run: sleep 10s

    - name: Check health of container
      run: docker exec -T githubtwin python -c "print('Application is running')"

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${env.DOCKER_USERNAME}/${env.DOCKER_REPO}:${env.IMAGE_TAG}

    - name: Stop and remove container
      run: |
        docker stop graphsp-web
        docker rm graphsp-web
