name: Eks Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: vikash98yadav
        DOCKER_PASSWORD: Vikash@17apr
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vikash98yadav/githubtwin
      
    - name: Install kubectl
      run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https gnupg2 curl
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

    - name: Docker Push
      run: docker push vikash98yadav/githubtwin

    - name: Update kube config
      run: aws eks update-kubeconfig --name githubtw
    - name: Deploy to EKS
      run: |
          kubectl apply -f deployment.yaml
          kubect1 apply -f service.yaml
